In [1]:
import pandas as pd
from tqdm.auto import tqdm

from project_package import data_collection as dc
from project_package import utility

In [33]:
df_demo = utility.read_data('demographic_feature')
df_demo. head()

         state_dcid  year  population_density state_name
0  wikidataId/Q1061  1991              210.74    Gujarat
1  wikidataId/Q1061  2001              258.49    Gujarat
2  wikidataId/Q1061  2002              263.81    Gujarat
3  wikidataId/Q1061  2003              269.13    Gujarat
4  wikidataId/Q1061  2004              274.45    Gujarat

In [35]:
df_demo['year'].unique()

array([1991, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2015, 2017, 2018, 2019, 2020, 2021, 2022])

In [ ]:
df_demo['year'].unique()

array([1991, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2015, 2017, 2018, 2019, 2020, 2021, 2022])

In [45]:
df_merged = utility.read_data('merged/ncr_weather_merged_data')
df_merged.shape

(150000, 54)

In [8]:
df_merged.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,time_drop,address_y,temperature_2m_drop,relative_humidity_2m_drop,dew_point_2m_drop,apparent_temperature_drop,precipitation_drop,rain_drop,snowfall_drop,wind_speed_10m_drop
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,2024-03-23 12:00:00,"DGD Jhilmil, Delhi, India",31.8,25.0,9.2,29.3,0.0,0.0,0.0,16.0
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,2024-11-29 18:00:00,"Gurgaon, Gurugram, HR, India",14.4,79.0,10.8,14.4,0.0,0.0,0.0,1.2
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,2024-08-23 08:00:00,"Malviya Nagar, Delhi, India",28.9,78.0,24.7,34.6,0.0,0.0,0.0,5.6
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,2024-10-21 17:00:00,"DGD, Inderlok, Delhi, India",24.7,77.0,20.5,27.8,0.0,0.0,0.0,7.0
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,2024-09-16 22:00:00,"Khan Market, Delhi, India",24.5,83.0,21.4,27.8,0.0,0.0,0.0,8.3

In [38]:

df =df_demo.copy()

# Pivot years into columns
df_wide = df.pivot(
    index=["state_dcid", "state_name"], 
    columns="year", 
    values="population_density"
).reset_index()

# Rename year columns as density_<year>
df_wide = df_wide.rename(columns={year: f"density_{year}" for year in df_wide.columns if isinstance(year, int)})

df_wide

# Merge wide table with summary
#df_final = pd.merge(df_wide, df_summary, on=["state_dcid","state_name"])
#print(df_final)

year,state_dcid,state_name,density_1991,density_2001,density_2002,density_2003,density_2004,density_2005,density_2006,density_2007,density_2008,density_2009,density_2010,density_2011,density_2012,density_2013,density_2015,density_2017,density_2018,density_2019,density_2020,density_2021,density_2022
0,wikidataId/Q1061,Gujarat,210.74,258.49,263.81,269.13,274.45,278.75,283.00,287.20,291.34,295.42,299.46,303.46,307.41,311.30,316.70,324.10,327.62,331.04,334.31,337.40,340.64
1,wikidataId/Q1159,Andhra Pradesh,142.22,162.97,165.32,167.67,170.01,171.43,172.79,174.33,176.05,177.73,179.38,180.63,182.21,183.76,318.72,323.71,326.10,328.42,330.67,332.85,334.89
2,wikidataId/Q1162,Arunachal Pradesh,10.33,13.11,13.49,13.86,14.25,14.58,14.93,15.27,15.63,15.99,16.37,16.75,17.15,17.54,15.51,15.85,16.01,16.17,16.32,16.47,16.62
3,wikidataId/Q1164,Assam,285.75,339.84,346.03,352.23,358.42,363.42,368.39,373.31,378.13,382.94,387.73,392.55,397.35,402.10,408.85,418.29,422.83,427.29,431.63,435.80,439.77
4,wikidataId/Q1165,Bihar,685.31,881.44,901.48,921.53,941.58,957.51,973.11,988.37,1003.30,1017.91,1032.17,1046.11,1059.72,1072.99,1091.00,1115.77,1127.75,1139.44,1150.90,1162.14,1172.54
5,wikidataId/Q1168,Chhattisgarh,130.30,154.11,157.72,161.33,164.95,167.91,171.61,174.57,178.27,181.23,184.92,188.62,192.32,196.02,189.03,193.70,195.93,198.10,200.21,202.21,204.19
6,wikidataId/Q1171,Goa,316.05,364.13,371.42,378.71,386.01,398.16,409.78,423.55,440.03,456.78,472.45,485.95,498.92,512.97,527.55,546.46,558.62,571.85,586.17,602.92,611.02
7,wikidataId/Q1174,Haryana,372.39,478.26,490.03,501.81,513.59,523.39,533.09,542.77,552.45,562.04,571.56,580.97,590.31,599.61,612.48,630.33,639.03,647.58,655.98,664.12,672.22
8,wikidataId/Q1177,Himachal Pradesh,92.88,109.17,110.83,112.48,114.13,115.42,116.72,117.96,119.20,120.38,121.55,123.96,125.21,126.49,126.40,128.45,129.43,130.39,131.32,132.22,133.06
9,wikidataId/Q1184,Jharkhand,274.03,338.03,345.21,352.40,359.57,365.26,370.93,376.45,381.84,387.21,392.57,398.01,403.43,408.81,416.53,427.39,432.58,437.65,442.56,447.25,451.84
10,wikidataId/Q1185,Karnataka,234.51,275.57,279.87,284.17,288.48,291.94,295.35,298.72,302.03,305.29,308.51,311.69,314.83,317.92,322.21,328.02,330.75,333.36,335.83,338.12,340.45
11,wikidataId/Q1186,Kerala,748.76,819.31,824.00,828.68,833.36,837.35,841.39,845.43,849.55,853.67,857.83,862.03,866.27,870.55,912.77,923.06,927.93,932.53,936.88,940.97,944.91
12,wikidataId/Q1188,Madhya Pradesh,157.56,195.78,200.51,205.24,209.96,213.82,217.66,221.47,225.24,228.98,232.71,236.43,240.13,243.81,248.97,256.17,259.67,263.11,266.46,269.70,272.87
13,wikidataId/Q1191,Maharashtra,256.53,314.84,320.99,327.16,333.32,338.50,343.63,348.77,353.93,359.05,364.11,369.07,373.99,378.89,385.59,394.88,399.48,404.03,408.53,412.99,417.27
14,wikidataId/Q1193,Manipur,82.28,102.75,105.57,108.34,111.17,113.63,116.14,118.74,121.33,124.02,126.75,129.53,132.40,135.31,114.79,117.30,118.51,119.72,120.84,121.96,123.03
15,wikidataId/Q1195,Meghalaya,79.14,103.39,106.56,109.77,112.93,115.74,118.64,121.58,124.62,127.74,130.95,134.20,137.55,140.98,122.30,124.97,126.27,127.51,128.72,129.92,131.08
16,wikidataId/Q1353,Delhi,6352.66,9339.85,9559.00,9778.83,9998.65,10190.83,10387.05,10585.97,10789.62,10996.63,11208.36,11423.47,11642.62,11865.81,13942.01,14764.67,15187.46,15619.69,16060.69,16510.45,16966.96
17,wikidataId/Q1356,West Bengal,767.06,903.37,917.37,931.36,945.35,955.93,966.37,976.42,985.95,995.30,1004.59,1013.92,1023.10,1032.02,1044.77,383.87,388.53,393.08,397.49,401.70,405.83
18,wikidataId/Q1363,Tripura,262.92,305.07,309.84,314.61,319.38,323.29,327.29,331.30,335.21,339.21,343.22,347.22,351.23,355.24,360.86,368.78,372.50,376.31,379.84,383.27,386.80
19,wikidataId/Q1437,Rajasthan,128.58,165.11,169.17,173.22,177.27,180.63,183.94,187.23,190.51,193.75,196.94,200.06,203.13,206.17,210.30,216.00,218.81,221.56,224.28,226.96,229.43
20,wikidataId/Q1445,Tamil Nadu,429.49,479.83,484.98,490.14,495.29,499.26,503.12,506.84,510.43,513.89,517.25,520.52,523.67,526.70,530.76,536.15,538.58,540.87,542.97,544.87,546.69
21,wikidataId/Q1498,Uttar Pradesh,548.14,689.82,706.71,723.61,740.50,754.86,769.23,783.69,798.27,812.86,827.41,841.87,856.32,870.81,891.02,919.23,933.18,946.97,960.56,973.86,986.50
22,wikidataId/Q1499,Uttarakhand,131.84,158.72,162.00,165.27,168.54,171.27,173.98,176.71,179.44,182.15,184.83,187.48,190.10,192.70,196.31,201.20,203.56,205.86,206.22,210.18,212.24
23,wikidataId/Q1502,Mizoram,32.73,42.17,43.50,44.83,46.16,47.34,48.57,49.81,51.09,52.37,53.75,55.12,56.54,57.97,49.86,50.95,51.47,51.99,52.46,52.94,53.41
24,wikidataId/Q1505,Sikkim,57.22,76.24,77.37,78.64,79.76,80.75,81.88,82.72,83.85,84.84,85.82,86.95,87.80,88.92,90.19,92.02,93.01,94.00,94.84,95.69,96.67
25,wikidataId/Q1599,Nagaland,72.98,120.03,115.81,111.65,107.43,109.17,110.98,112.79,114.66,116.53,117.74,120.94,123.95,127.03,141.99,145.06,146.57,148.02,149.41,150.79,152.12
26,wikidataId/Q22048,Odisha,203.33,236.37,240.04,243.71,247.38,250.64,253.93,257.28,260.68,264.13,267.63,271.18,274.79,278.45,270.62,274.93,277.01,279.05,281.05,283.02,284.82
27,wikidataId/Q22424,Punjab,402.72,483.68,494.62,505.56,516.50,526.05,535.78,545.69,555.78,566.04,576.51,587.17,591.64,602.58,572.77,583.22,588.24,593.07,597.69,602.10,606.45
28,wikidataId/Q26927,Lakshadweep,1625.00,1895.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.41,NaN,NaN,2468.75,2562.50,2593.75,2625.00,2656.25,2687.50,2687.50
29,wikidataId/Q40888,Andaman and Nicobar Islands,34.06,43.16,44.85,46.67,48.37,50.07,51.76,53.58,55.52,57.46,59.28,60.86,62.43,64.01,65.83,68.25,69.71,71.28,72.86,74.80,76.01
30,wikidataId/Q66278313,Jammu and Kashmir,77.30,100.05,101.94,103.82,105.70,107.28,108.84,110.39,111.95,113.49,115.00,116.44,117.88,119.31,121.21,123.73,124.92,126.05,127.12,128.09,129.07
31,wikidataId/Q66743,Puducherry,1686.85,2033.40,2081.42,2127.35,2175.37,2217.12,2258.87,2300.63,2344.47,2388.31,2434.24,2638.83,2703.55,2772.44,3394.57,3617.95,3753.65,3899.79,4058.46,4233.82,4352.82

In [39]:
df_wide.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state_dcid    32 non-null     object
 1   state_name    32 non-null     object
 2   density_1991  32 non-null     float64
 3   density_2001  32 non-null     float64
 4   density_2002  31 non-null     float64
 5   density_2003  31 non-null     float64
 6   density_2004  31 non-null     float64
 7   density_2005  31 non-null     float64
 8   density_2006  31 non-null     float64
 9   density_2007  31 non-null     float64
 10  density_2008  31 non-null     float64
 11  density_2009  31 non-null     float64
 12  density_2010  31 non-null     float64
 13  density_2011  32 non-null     float64
 14  density_2012  31 non-null     float64
 15  density_2013  31 non-null     float64
 16  density_2015  32 non-null     float64
 17  density_2017  32 non-null     float64
 18  density_2018  32 non-null     float64
 19  density_2019  32 non-null     float64
 20  density_2020  32 non-null     float64
 21  density_2021  32 non-null     float64
 22  density_2022  32 non-null     float64
dtypes: float64(21), object(2)
memory usage: 5.9+ KB

In [15]:
import pandas as pd

pd.set_option("display.max_columns", None)

df_merged.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,pick_longitude,pick_latitude,pick_address,pick_region,pick_locality,drop_longitude,drop_latitude,drop_address,drop_region,drop_locality,datetime,date,hour,time_pickup,address_x,temperature_2m_pickup,relative_humidity_2m_pickup,dew_point_2m_pickup,apparent_temperature_pickup,precipitation_pickup,rain_pickup,snowfall_pickup,wind_speed_10m_pickup,time_drop,address_y,temperature_2m_drop,relative_humidity_2m_drop,dew_point_2m_drop,apparent_temperature_drop,precipitation_drop,rain_drop,snowfall_drop,wind_speed_10m_drop
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.164401,28.567593,"Palam Marg, Delhi, India",Delhi,Delhi,77.311751,28.670789,"DGD Jhilmil, Delhi, India",Delhi,Delhi,2024-03-23 12:29:38,2024-03-23,12,2024-03-23 12:00:00,"Palam Marg, Delhi, India",31.8,24.0,8.9,29.0,0.0,0.0,0.0,16.6,2024-03-23 12:00:00,"DGD Jhilmil, Delhi, India",31.8,25.0,9.2,29.3,0.0,0.0,0.0,16.0
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI,73.897280,18.552377,"Shastri Nagar, Pune, MH, India",Maharashtra,Pune,77.011193,28.489101,"Gurgaon, Gurugram, HR, India",Haryana,Gurugram,2024-11-29 18:01:39,2024-11-29,18,2024-11-29 18:00:00,"Shastri Nagar, Pune, MH, India",19.1,51.0,8.6,17.7,0.0,0.0,0.0,7.3,2024-11-29 18:00:00,"Gurgaon, Gurugram, HR, India",14.4,79.0,10.8,14.4,0.0,0.0,0.0,1.2
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,NaN,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card,82.311070,26.281650,"Khandsara, UP, India",Uttar Pradesh,Khandsara,77.212385,28.534341,"Malviya Nagar, Delhi, India",Delhi,Delhi,2024-08-23 08:56:10,2024-08-23,8,2024-08-23 08:00:00,"Khandsara, UP, India",30.8,75.0,25.8,36.9,0.2,0.2,0.0,7.6,2024-08-23 08:00:00,"Malviya Nagar, Delhi, India",28.9,78.0,24.7,34.6,0.0,0.0,0.0,5.6
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,NaN,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI,74.843239,12.863404,"Mangaluru Central, Mangalore, KA, India",Karnataka,Mangalore,77.167640,28.672408,"DGD, Inderlok, Delhi, India",Delhi,Delhi,2024-10-21 17:17:25,2024-10-21,17,2024-10-21 17:00:00,"Mangaluru Central, Mangalore, KA, India",24.8,96.0,24.1,30.4,0.0,0.0,0.0,4.0,2024-10-21 17:00:00,"DGD, Inderlok, Delhi, India",24.7,77.0,20.5,27.8,0.0,0.0,0.0,7.0
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,NaN,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI,83.947149,21.386179,"Village, OR, India",Odisha,NaN,77.229128,28.602245,"Khan Market, Delhi, India",Delhi,Delhi,2024-09-16 22:08:00,2024-09-16,22,2024-09-16 22:00:00,"Village, OR, India",24.6,93.0,23.4,28.7,0.0,0.0,0.0,10.9,2024-09-16 22:00:00,"Khan Market, Delhi, India",24.5,83.0,21.4,27.8,0.0,0.0,0.0,8.3

In [17]:
# Count how many unique values
num_unique = df_merged['pick_region'].nunique()

# List unique values
unique_values = df_merged['pick_region'].unique()

# Count frequencies of each unique value
value_counts = df_merged['pick_region'].value_counts()

print("Number of unique regions:", num_unique)
print("\nUnique regions:", unique_values)
print("\nCounts per region:\n", value_counts)

Number of unique regions: 24

Unique regions: ['Delhi' 'Maharashtra' 'Uttar Pradesh' 'Karnataka' 'Odisha' 'Punjab'
 'Bihar' 'West Bengal' 'Tamil Nadu' 'Jammu and Kashmir' 'Andhra Pradesh'
 'Haryana' 'Himachal Pradesh' 'Gujarat' 'Uttarakhand' 'Kerala' nan 'Assam'
 'Chhattisgarh' 'Madhya Pradesh' 'Rajasthan' 'Telangana' 'Azad Kashmir'
 'Jharkhand' 'Chandigarh']

Counts per region:
 pick_region
Delhi                56374
Uttar Pradesh        19653
Haryana              13643
Tamil Nadu            7593
Bihar                 6543
Maharashtra           6053
West Bengal           4599
Gujarat               4527
Rajasthan             4343
Madhya Pradesh        3038
Punjab                2795
Karnataka             2754
Kerala                2637
Assam                 2338
Andhra Pradesh        2067
Jammu and Kashmir     1905
Uttarakhand           1833
Telangana             1624
Chhattisgarh          1023
Jharkhand              967
Himachal Pradesh       736
Azad Kashmir           575
Odisha                 561
Chandigarh              57
Name: count, dtype: int64

In [ ]:
demo_state = df_summary['state_name'].unique()
ncr_state = df_merged['pick_region'].unique()

# Convert to sets
demo_set = set(demo_state)
ncr_set = set(ncr_state)

# Check if they are the same
print("Are they exactly the same?", demo_set == ncr_set)

# Show differences
print("\nIn demo_state but not in ncr_state:", demo_set - ncr_set)
print("In ncr_state but not in demo_state:", ncr_set - demo_set)

Are they exactly the same? False

In demo_state but not in ncr_state: {'Sikkim', 'Andaman and Nicobar Islands', 'Manipur', 'Mizoram', 'Meghalaya', 'Nagaland', 'Goa', 'Lakshadweep', 'Puducherry', 'Tripura', 'Arunachal Pradesh'}
In ncr_state but not in demo_state: {nan, 'Chandigarh', 'Telangana', 'Azad Kashmir'}

	•	Chandigarh → a Union Territory in northern India, not a state. It serves as the joint capital of Punjab and Haryana.
	•	Telangana → an official state of India, formed in 2014 when it was carved out of Andhra Pradesh. Capital: Hyderabad.
	•	Azad Kashmir → not an Indian state. It is a self-governing administrative territory under Pakistani control, officially called “Azad Jammu and Kashmir (AJK).” India claims it as part of the larger Jammu & Kashmir region, but it is not an Indian state or union territory.

In [24]:
demo_sorted = sorted(set(demo_state))
print(demo_sorted)

['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [ ]:
df_merged_test = df_merged[df_merged['pick_region'].isin(['Chandigarh', 'Telangana', 'Azad Kashmir'])]
df_merged_test.shape
#Chandigarh -> Not a state, it's a Union Territory and capital of Punjab and Haryana.
#Telangana ->Andhra Pradesh. was split into Telangana and Andhra Pradesh in 2014.
#Azad Kashmir -> Jammu and Kashmir

(2256, 54)

In [48]:
df_merged = df_merged.dropna(subset=['pick_address'])
df_merged.shape
#150000-148238 = 1762 rows with missing pick_address

(148294, 54)

In [55]:
df_merged_test

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,pick_longitude,pick_latitude,pick_address,pick_region,pick_locality,drop_longitude,drop_latitude,drop_address,drop_region,drop_locality,datetime,date,hour,time_pickup,address_x,temperature_2m_pickup,relative_humidity_2m_pickup,dew_point_2m_pickup,apparent_temperature_pickup,precipitation_pickup,rain_pickup,snowfall_pickup,wind_speed_10m_pickup,time_drop,address_y,temperature_2m_drop,relative_humidity_2m_drop,dew_point_2m_drop,apparent_temperature_drop,precipitation_drop,rain_drop,snowfall_drop,wind_speed_10m_drop
188,2024-12-17,19:11:24,"""CNR1867567""",Incomplete,"""CID6010303""",Premier Sedan,Qutub Minar,Ghitorni,7.2,18.4,NaN,NaN,NaN,NaN,1.0,Customer Demand,635.0,6.57,NaN,NaN,UPI,78.455283,17.488895,"Qutubullapur, Hyderabad, TG, India",Telangana,Hyderabad,77.152978,28.495298,"NBCC Ghitorni, Delhi, India",Delhi,Delhi,2024-12-17 19:11:24,2024-12-17,19,2024-12-17 19:00:00,"Qutubullapur, Hyderabad, TG, India",16.9,71.0,11.6,16.8,0.0,0.0,0.0,4.2,2024-12-17 19:00:00,"NBCC Ghitorni, Delhi, India",12.6,76.0,8.5,11.6,0.0,0.0,0.0,4.0
216,2024-10-28,15:46:27,"""CNR5629774""",Completed,"""CID8747096""",Go Mini,Ghaziabad,Udyog Vihar,3.2,30.8,NaN,NaN,NaN,NaN,NaN,NaN,54.0,31.49,4.6,4.9,Cash,73.802170,33.704660,"Ghaziabad, JK, India",Azad Kashmir,Ghaziabad,77.037500,28.470500,"The Lemon Tree Hotel - Udyog Vihar, Gurugram, ...",Haryana,Gurugram,2024-10-28 15:46:27,2024-10-28,15,2024-10-28 15:00:00,"Ghaziabad, JK, India",15.0,82.0,12.0,15.2,0.0,0.0,0.0,2.6,2024-10-28 15:00:00,"The Lemon Tree Hotel - Udyog Vihar, Gurugram, ...",25.4,69.0,19.4,27.8,0.0,0.0,0.0,8.3
259,2024-06-01,08:04:36,"""CNR5483670""",Completed,"""CID3570152""",Go Sedan,Panchsheel Park,Sarai Kale Khan,8.4,19.7,NaN,NaN,NaN,NaN,NaN,NaN,427.0,37.07,4.1,4.9,Cash,78.466188,17.376458,"Panchsheel, Hyderabad, TG, India",Telangana,Hyderabad,77.290745,28.673679,"Makki Sarai Railway Road, Delhi, India",Delhi,Delhi,2024-06-01 08:04:36,2024-06-01,8,2024-06-01 08:00:00,"Panchsheel, Hyderabad, TG, India",39.3,27.0,16.8,41.8,0.0,0.0,0.0,9.2,2024-06-01 08:00:00,"Makki Sarai Railway Road, Delhi, India",44.5,9.0,5.2,41.5,0.0,0.0,0.0,14.6
500,2024-11-02,12:14:07,"""CNR5206507""",Completed,"""CID9160368""",Uber XL,Ghaziabad,Mandi House,3.9,25.2,NaN,NaN,NaN,NaN,NaN,NaN,407.0,19.99,3.7,4.9,UPI,73.802170,33.704660,"Ghaziabad, JK, India",Azad Kashmir,Ghaziabad,77.233778,28.625848,"Mandi House, Delhi, India",Delhi,Delhi,2024-11-02 12:14:07,2024-11-02,12,2024-11-02 12:00:00,"Ghaziabad, JK, India",16.8,57.0,8.3,16.2,0.0,0.0,0.0,1.7,2024-11-02 12:00:00,"Mandi House, Delhi, India",25.7,57.0,16.5,26.6,0.0,0.0,0.0,9.4
520,2024-02-10,08:25:19,"""CNR9190112""",Completed,"""CID2588384""",Auto,Ghaziabad,Moti Nagar,3.3,25.8,NaN,NaN,NaN,NaN,NaN,NaN,131.0,15.83,3.1,4.3,Credit Card,73.802170,33.704660,"Ghaziabad, JK, India",Azad Kashmir,Ghaziabad,77.139422,28.661482,"Moti Nagar, Delhi, India",Delhi,Delhi,2024-02-10 08:25:19,2024-02-10,8,2024-02-10 08:00:00,"Ghaziabad, JK, India",11.7,34.0,-3.5,9.3,0.0,0.0,0.0,4.3,2024-02-10 08:00:00,"Moti Nagar, Delhi, India",19.0,56.0,10.0,18.9,0.0,0.0,0.0,7.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149750,2024-04-16,04:15:42,"""CNR7211951""",Cancelled by Driver,"""CID5880499""",Go Mini,Shastri Park,Yamuna Bank,10.3,NaN,NaN,NaN,1.0,More than permitted people in there,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.135717,18.432282,"Shastri Road, Karimnagar, TG, India",Telangana,Karimnagar,80.266113,12.990320,"Yamuna Street, Chennai, TN, India",Tamil Nadu,Chennai,2024-04-16 04:15:42,2024-04-16,4,2024-04-16 04:00:00,"Shastri Road, Karimnagar, TG, India",33.5,38.0,17.3,35.5,0.0,0.0,0.0,5.4,2024-04-16 04:00:00,"Yamuna Street, Chennai, TN, India",33.2,53.0,22.3,37.4,0.0,0.0,0.0,9.4
149813,2024-11-20,00:30:54,"""CNR9281992""",Completed,"""CID4595219""",Go Mini,Ghaziabad,Badarpur,10.5,23.4,NaN,NaN,NaN,NaN,NaN,NaN,404.0,13.84,4.3,4.6,Cash,73.802170,33.704660,"Ghaziabad, JK, India",Azad Kashmir,Ghaziabad,77.093350,29.962750,"Badarpur, HR, India",Haryana,Badarpur,2024-11-20 00:30:54,2024-11-20,0,2024-11-20 00:00:00,"Ghaziabad, JK, India",9.7,25.0,-9.5,6.2,0.0,0.0,0.0,1.6,2024-11-20 00:00:00,"Badarpur, HR, India",11.5,92.0,10.3,10.6,0.0,0.0,0.0,6.9
149877,2024-02-08,19:56:12,"""CNR6210068""",Completed,"""CID4672214""",eBike,Ghaziabad,Kanhaiya Nagar,9.2,18.7,NaN,NaN,NaN,NaN,NaN,NaN,249.0,36.06,4.1,3.2,Debit Card,73.802170,33.704660,"Ghaziabad, JK, India",Azad Kashmir,Ghaziabad,77.099220,27.423970,"Nagar, RJ, India",Rajasthan,Nagar,2024-02-08 19:56:12,2024-02-08,19,2024-02-08 19:00:00,"Ghaziabad, JK, India",9.2,9.0,-21.6,4.9,0.0,0.0,0.0,3.0,2024-02-08 19:00:00,"Nagar, RJ, India",9.7,64.0,3.3,6.8,0.0,0.0,0.0,9.6
149930,2024-02-07,12:03:31,"""CNR5854960""",Completed,"""CID4196514""",eBike,Ghaziabad,Tis Hazari,14.5,38.4,NaN,NaN,NaN,NaN,NaN,NaN,815.0,24.74,4.7,4.5,UPI,73.802170,33.704660,"Ghaziabad, JK, India",Azad Kashmir,Ghaziabad,77.215738,28.665888,"Tis Hazari, Delhi, India",Delhi,Delhi,2024-02-07 12:03:31,2024-02-07,12,2024-02-07 12:00:00,"Ghaziabad, JK, India",5.5,47.0,-4.8,2.0,0.0,0.0,0.0,5.2,2024-02-07 12:00:00,"Tis Hazari, Delhi, India",15.4,61.0,7.8,12.7,0.0,0.0,0.0,14.9
149955,2024-03-24,09:45:35,"""CNR3884070""",Completed,"""CID3117846""",Premier Sedan,Qutub Minar,IGNOU Road,9.9,21.5,NaN,NaN,NaN,NaN,NaN,NaN,461.0,48.50,4.9,4.3,Cash,78.455283,17.488895,"Qutubullapur, Hyderabad, TG, India",Telangana,Hyderabad,77.203946,28.512954,"IGNOU Road, Delhi, India",Delhi,Delhi,2024-03-24 09:45:35,2024-03-24,9,2024-03-24 09:00:00,"Qutubullapur, Hyderabad, TG, India",35.2,25.0,12.3,35.1,0.0,0.0,0.0,11.9,2024-03-24 09:00:00,"IGNOU Road, Delhi, India",30.4,24.0,7.4,25.5,0.0,0.0,0.0,28.9

In [56]:
df_merged_demo = pd.merge(df_merged, df_wide, left_on='pick_region', right_on='state_name', how='left')

In [57]:
df_merged_demo.shape

(148294, 77)

In [60]:
#remove rows with missing state_name

df_merged_demo_clean = df_merged_demo.dropna(subset=['state_name'])
#utility.save_dataframe(df_merged,file_name='ncr_weather_merged_data',directory='datasets/raw/merged')

In [62]:
df_merged_demo_clean.shape
#148294-145982 = 2312 rows with missing state_name

(145982, 77)

In [63]:
utility.save_dataframe(df_merged_demo_clean,file_name='df_merged_demo',directory='datasets/raw/merged')

Save data completed.